"""update all migration

Revision ID: 09fafe097408
Revises: ead2c9f2f61d
Create Date: 2025-12-18 22:43:59.797531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09fafe097408'
down_revision: Union[str, None] = 'ead2c9f2f61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_partners', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('payment_partners', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_payment_partners_id'), 'payment_partners', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_partners_id'), table_name='payment_partners')
    op.drop_column('payment_partners', 'updated_at')
    op.drop_column('payment_partners', 'created_at')
    # ### end Alembic commands ###
