"""change type to method

Revision ID: 1b27a0a7de30
Revises: f53881b372f2
Create Date: 2026-02-12 01:07:58.177301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b27a0a7de30'
down_revision: Union[str, Sequence[str], None] = 'f53881b372f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True))
    op.add_column('transactions', sa.Column('receiving_method', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('transactions', 'recipient_type')
    op.drop_column('transactions', 'payment_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('recipient_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'receiving_method')
    op.drop_column('transactions', 'payment_method')
    # ### end Alembic commands ###
