"""add field

Revision ID: 27ad54f767be
Revises: 6cd5b470a84f
Create Date: 2025-04-14 20:20:24.861449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ad54f767be'
down_revision: Union[str, None] = '6cd5b470a84f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('include_fee', sa.BOOLEAN(), nullable=True))
    op.add_column('transactions', sa.Column('feeAmount', sa.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'feeAmount')
    op.drop_column('transactions', 'include_fee')
    # ### end Alembic commands ###
