"""Initail migration

Revision ID: 30aec6f94a56
Revises: 
Create Date: 2025-11-23 06:24:32.060607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30aec6f94a56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hash_password', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('profile_picture_url', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('currency_id', sa.Uuid(), nullable=False),
    sa.Column('dial_code', sa.VARCHAR(length=4), nullable=True),
    sa.Column('flag', sa.VARCHAR(), nullable=False),
    sa.Column('phone_number_length', sa.INTEGER(), nullable=False),
    sa.Column('phone_format_example', sa.VARCHAR(length=20), nullable=True),
    sa.Column('can_send_from', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('can_send_to', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ex_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_currency_id', sa.Uuid(), nullable=False),
    sa.Column('to_currency_id', sa.Uuid(), nullable=False),
    sa.Column('rate', sa.DECIMAL(), nullable=False),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['from_currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['to_currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency_id', 'to_currency_id', name='unique_currency_pair')
    )
    op.create_index('idx_from_to_currency', 'ex_rates', ['from_currency_id', 'to_currency_id'], unique=False)
    op.create_table('fcm_tokens',
    sa.Column('pk', sa.UUID(), nullable=False),
    sa.Column('token', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('token')
    )
    op.create_table('fees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_country_id', sa.Uuid(), nullable=False),
    sa.Column('to_country_id', sa.Uuid(), nullable=False),
    sa.Column('fee_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('fee_value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('min_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('max_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['from_country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_from_to', 'fees', ['from_country_id', 'to_country_id'], unique=False)
    op.create_table('payment_partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('can_send', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('can_receive', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payment_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_partner_id', sa.Uuid(), nullable=False),
    sa.Column('account_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('account_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['payment_partner_id'], ['payment_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('reference', sa.VARCHAR(length=12), nullable=True),
    sa.Column('sender_country_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_country_id', sa.Uuid(), nullable=False),
    sa.Column('sender_partner_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_partner_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_full_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('receiver_phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('receiver_email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sender_amount', sa.DECIMAL(precision=15, scale=0), nullable=False),
    sa.Column('sender_currency', sa.VARCHAR(length=10), nullable=False),
    sa.Column('receiver_amount', sa.DECIMAL(precision=15, scale=0), nullable=False),
    sa.Column('receiver_currency', sa.VARCHAR(length=10), nullable=True),
    sa.Column('exchange_rate', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('applied_fee', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_to_pay', sa.DECIMAL(precision=15, scale=0), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('notes', sa.VARCHAR(length=255), nullable=True),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expired_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receiver_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['receiver_partner_id'], ['payment_partners.id'], ),
    sa.ForeignKeyConstraint(['sender_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_partner_id'], ['payment_partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index('idx_transaction_status', 'transactions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transaction_status', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('payment_accounts')
    op.drop_table('payment_partners')
    op.drop_index('idx_from_to', table_name='fees')
    op.drop_table('fees')
    op.drop_table('fcm_tokens')
    op.drop_index('idx_from_to_currency', table_name='ex_rates')
    op.drop_table('ex_rates')
    op.drop_table('countries')
    op.drop_table('users')
    op.drop_table('currencies')
    # ### end Alembic commands ###
