"""remove pin

Revision ID: 34160dbb31b6
Revises: aeecdec74094
Create Date: 2025-04-16 14:49:54.217754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34160dbb31b6'
down_revision: Union[str, None] = 'aeecdec74094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_pin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_pin', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
