"""add timestamps to transaction

Revision ID: 3dbdad1ae76d
Revises: 007d9374a33a
Create Date: 2026-02-21 14:10:12.612657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3dbdad1ae76d'
down_revision: Union[str, Sequence[str], None] = '007d9374a33a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('new_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('changed_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.VARCHAR(length=255), nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('transactions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('transactions', sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('expired_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('processed_by_admin_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'users', ['processed_by_admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'processed_by_admin_id')
    op.drop_column('transactions', 'expired_at')
    op.drop_column('transactions', 'cancelled_at')
    op.drop_column('transactions', 'completed_at')
    op.drop_column('transactions', 'processed_at')
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'created_at')
    op.drop_table('transaction_status_history')
    # ### end Alembic commands ###
