"""change type

Revision ID: 466641715ba0
Revises: 8835aed0165b
Create Date: 2025-04-15 16:06:14.390002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466641715ba0'
down_revision: Union[str, None] = '8835aed0165b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'sender_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('transactions', 'receiver_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('transactions', 'fee_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('users', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('role', sa.VARCHAR(), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'role')
    op.drop_column('users', 'email')
    op.alter_column('transactions', 'fee_amount',
               existing_type=sa.INTEGER(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'receiver_amount',
               existing_type=sa.INTEGER(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('transactions', 'sender_amount',
               existing_type=sa.INTEGER(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
