"""new migration

Revision ID: 497784318422
Revises: 
Create Date: 2025-12-18 13:25:13.531498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '497784318422'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_fr', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_code'), 'currencies', ['code'], unique=True)
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'SUPER_ADMIN', 'USER', 'AGENT', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING', name='userstatus', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('flag', sa.String(length=10), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.Column('dial_code', sa.String(length=10), nullable=False),
    sa.Column('phone_number_length', sa.Integer(), nullable=False),
    sa.Column('phone_format_example', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_send_from', sa.Boolean(), nullable=False),
    sa.Column('can_send_to', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_table('exchange_rates',
    sa.Column('from_currency_id', sa.UUID(), nullable=False),
    sa.Column('to_currency_id', sa.UUID(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('inverse_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['to_currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency_id', 'to_currency_id', name='uq_currency_pair_current')
    )
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference', sa.VARCHAR(length=50), nullable=False),
    sa.Column('sender_country', sa.VARCHAR(length=200), nullable=False),
    sa.Column('receiver_country', sa.VARCHAR(length=200), nullable=False),
    sa.Column('sender_partner', sa.VARCHAR(length=20), nullable=False),
    sa.Column('receiver_partner', sa.VARCHAR(length=200), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_full_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('receiver_phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('receiver_email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sender_amount', sa.DECIMAL(precision=15, scale=0), nullable=False),
    sa.Column('sender_currency', sa.VARCHAR(length=10), nullable=False),
    sa.Column('receiver_amount', sa.DECIMAL(precision=15, scale=0), nullable=False),
    sa.Column('receiver_currency', sa.VARCHAR(length=10), nullable=False),
    sa.Column('exchange_rate', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('applied_fee', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_to_pay', sa.DECIMAL(precision=15, scale=0), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('notes', sa.VARCHAR(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transfer_status', 'transfers', ['status'], unique=False)
    op.create_index(op.f('ix_transfers_reference'), 'transfers', ['reference'], unique=True)
    op.create_table('fees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_country_id', sa.UUID(), nullable=False),
    sa.Column('to_country_id', sa.UUID(), nullable=False),
    sa.Column('fee_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('fee_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['to_country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_send', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('can_receive', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payment_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_partner_id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('account_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_partner_id'], ['payment_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_accounts')
    op.drop_table('payment_partners')
    op.drop_table('fees')
    op.drop_index(op.f('ix_transfers_reference'), table_name='transfers')
    op.drop_index('idx_transfer_status', table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_code'), table_name='currencies')
    op.drop_table('currencies')
    # ### end Alembic commands ###
