"""add constraint

Revision ID: 6cd5b470a84f
Revises: 2040e13877e2
Create Date: 2025-04-13 18:18:03.879522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd5b470a84f'
down_revision: Union[str, None] = '2040e13877e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_currency_pair', 'ex_rates', ['from_currency_id', 'to_currency_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_currency_pair', 'ex_rates', type_='unique')
    # ### end Alembic commands ###
