"""modified fee_amount

Revision ID: 8835aed0165b
Revises: 27ad54f767be
Create Date: 2025-04-14 21:46:18.148750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8835aed0165b'
down_revision: Union[str, None] = '27ad54f767be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('fee_amount', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_column('transactions', 'feeAmount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('feeAmount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'fee_amount')
    # ### end Alembic commands ###
