"""delete inverse_rate

Revision ID: 93cbec5bdf7e
Revises: db8cd58f5882
Create Date: 2025-12-20 09:24:01.515609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93cbec5bdf7e'
down_revision: Union[str, None] = 'db8cd58f5882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_rates', 'inverse_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_rates', sa.Column('inverse_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
