"""change user

Revision ID: aeecdec74094
Revises: 2d9838341501
Create Date: 2025-04-16 14:47:25.766625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeecdec74094'
down_revision: Union[str, None] = '2d9838341501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_pin', sa.INTEGER(), nullable=True))
    op.drop_column('users', 'pin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'hashed_pin')
    # ### end Alembic commands ###
