"""comment country_code

Revision ID: bf5173bbe394
Revises: 497784318422
Create Date: 2025-12-18 13:45:22.578785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5173bbe394'
down_revision: Union[str, None] = '497784318422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
