"""fix relationship...

Revision ID: ddfc7ecebd1a
Revises: 34160dbb31b6
Create Date: 2025-04-16 17:17:03.048909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddfc7ecebd1a'
down_revision: Union[str, None] = '34160dbb31b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sender_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'users', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'sender_id')
    # ### end Alembic commands ###
