"""modify exchange rate

Revision ID: ead2c9f2f61d
Revises: bf5173bbe394
Create Date: 2025-12-18 14:08:35.364866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead2c9f2f61d'
down_revision: Union[str, None] = 'bf5173bbe394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currencies', 'zone')
    op.drop_column('currencies', 'name_fr')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('name_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('currencies', sa.Column('zone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
